[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/config/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
