[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "npm start"
  port = 5089

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Redirect auth calls to Netlify Functions  
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

# SPA fallback - serve index.html for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
